# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

posterior_sampling <- function(y, X, tau = 1, family = 0L, mcmc = 100L, print_every = 100L) {
    .Call(`_simpa_posterior_sampling`, y, X, tau, family, mcmc, print_every)
}

